name: CI/CD Build mlops framework

on:
  push:
    branches:
      - main

jobs:
  Unit-Test:
    name: unit-test
    runs-on: [ ubuntu-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt install -y python3.8-venv

    - name: run-tests
      id: test-sdk
      env:
        AWS_DEFAULT_REGION: eu-west-1
      run: |
        cd ./source
        chmod +x ./run-all-tests.sh
        ./run-all-tests.sh
       
  Build:
    name: build
    runs-on: [ ubuntu-latest ]
    needs: Unit-Test

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt install -y python3.8-venv npm nodejs

    - name: build
      id: build-distibution
      env:
        DIST_OUTPUT_BUCKET: aws-mlops-framework-eu-west-1
        SOLUTION_NAME: aws-mlops-framework
        VERSION: v1.3.0
      run: |
        cd ./deployment
        chmod +x ./build-s3-dist.sh
        ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION

