name: CI/CD Build mlops framework

on:
  push:
    branches:
      - main

jobs:
  Unit-Test:
    name: unit-test
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run-tests
      id: build-sdk
      env:
        AWS_DEFAULT_REGION: us-east-1
      run: |
        cd source
        chmod +x ./run-all-tests.sh
        ./run-all-tests.sh
